# Generated by Django 3.1 on 2020-08-29 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_first_name', models.CharField(max_length=50, null=True)),
                ('employee_last_name', models.CharField(max_length=50, null=True)),
                ('employee_Date_of_birth', models.DateField()),
                ('employee_Designation', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PresentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_line_1', models.CharField(max_length=50, null=True)),
                ('Address_line_2', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('Pin', models.IntegerField()),
                ('Country', models.CharField(max_length=50, null=True)),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_line_1', models.CharField(max_length=50, null=True)),
                ('Address_line_2', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('Pin', models.IntegerField()),
                ('Country', models.CharField(max_length=50, null=True)),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_line_1', models.CharField(max_length=50, null=True)),
                ('Address_line_2', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('Pin', models.IntegerField()),
                ('Country', models.CharField(max_length=50, null=True)),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testApp.employee')),
            ],
        ),
    ]
